---
- name: install EPEL package
  package:
    name: epel-release
    state: present
  become: true
  register: epel_install_epel_package
  until: epel_install_epel_package is succeeded
  retries: 5

- name: yum update cache
  yum:
    update_cache: yes

- name: importing EPEL GPG key
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present
  become: true
